// Weekly report — executive commentary from the Brandzp BI agent.
//
// Feeds the BI agent a compact summary of the week's KPIs (Meta Ads,
// affiliates, Instagram, alerts) and asks for 3 insights + 3 prescribed
// actions. The output renders at the very top of the weekly PDF so the
// founder reads "what happened + what to do" before scrolling into the
// per-brand details.
//
// Why the BI agent (not Anthropic direct):
//   - The agent is domain-tuned for our analytics shape
//   - Future-proof: when the agent gets access to historical Brandzp data
//     it can frame insights ("this is the worst CPC since week 17") that
//     a stateless LLM can't
//
// Fallback: returns null (and the section just hides) if BI agent is
// unconfigured OR throws. Never blocks PDF generation.

import { askCreativeAgentJson, askBiAgentJson, isBiAgentConfigured } from "@/lib/clients/bi-agent-client";
import { COMPETITOR_INTEL_LATEST } from "@/lib/data/competitor-intel-latest";
import type { MetaAdsWeeklyReport } from "@/lib/services/meta-ads-report-service";
import type { AffiliateDeepDiveReport } from "@/lib/services/affiliate-deep-dive-service";
import type { RestockHeroAlertReport } from "@/lib/services/restock-hero-alert-service";
import type { RoasCollapseReport } from "@/lib/services/roas-collapse-service";
import type { CompetitorWeekSection } from "@/lib/services/competitor-intel-service";

export interface BiWeeklyCommentary {
  // 1-sentence headline, e.g. "Strong ROAS week, but stockout risk on hero #2."
  headline: string;
  // 3 short insights (what the agent noticed in the data).
  insights: string[];
  // 3 prescribed actions for the founder this week.
  actions: string[];
  // Provenance so the UI can label "Generated by Brandzp BI agent at ...".
  agent: string;
  generatedAt: string;
}

export interface BiWeeklyCommentaryInput {
  storeName: string | null;
  periodStart: string;
  periodEnd: string;
  locale: "he" | "en";
  metaAds: MetaAdsWeeklyReport | null;
  affiliateDeepDive: AffiliateDeepDiveReport | null;
  restockAlerts: RestockHeroAlertReport | null;
  roasCollapseAlerts: RoasCollapseReport | null;
  // Competitor promo/pricing context (RivalSweeper Feed A). Required (not
  // optional) on purpose: both call sites — weekly-report-service AND the
  // print page — must pass it, so the two render paths can't drift.
  competitorWeek: CompetitorWeekSection | null;
  // Live RivalSweeper activity (ads volume/themes, press, homepage pushes).
  competitorActivity?: import("@/lib/clients/rivalsweeper-client").CompetitorActivityEntry[] | null;
}

// Build a compact, structured digest the agent can reason over. We DON'T
// dump the entire bundle — most fields are redundant. We extract the
// "facts a smart human would pick out before writing the executive summary."
function buildDigest(input: BiWeeklyCommentaryInput): string {
  const lines: string[] = [];
  lines.push(`Store: ${input.storeName ?? "(unknown)"}`);
  lines.push(`Period: ${input.periodStart} → ${input.periodEnd}`);
  lines.push("");

  // ── Meta Ads totals + per-brand ROAS ──────────────────────────────
  if (input.metaAds) {
    const m = input.metaAds;
    const totals = m.brands.reduce(
      (acc, b) => ({
        spend: acc.spend + b.kpis.spend,
        purchases: acc.purchases + b.kpis.purchases,
        impressions: acc.impressions + b.kpis.impressions,
        clicks: acc.clicks + b.kpis.clicks,
        revenue: acc.revenue + (b.kpis.purchaseRoas != null ? b.kpis.spend * b.kpis.purchaseRoas : 0)
      }),
      { spend: 0, purchases: 0, impressions: 0, clicks: 0, revenue: 0 }
    );
    const totalRoas = totals.spend > 0 ? totals.revenue / totals.spend : null;
    lines.push("Meta Ads:");
    lines.push(`  Total spend: ₪${Math.round(totals.spend).toLocaleString()}`);
    lines.push(`  Total purchases (Meta-attributed): ${totals.purchases}`);
    lines.push(`  Weighted ROAS: ${totalRoas != null ? totalRoas.toFixed(2) + "×" : "n/a"}`);
    if (m.brands.length > 0) {
      lines.push("  By brand (ranked by spend):");
      const ranked = [...m.brands].sort((a, b) => b.kpis.spend - a.kpis.spend).slice(0, 5);
      for (const b of ranked) {
        const r = b.kpis.purchaseRoas;
        lines.push(
          `    - ${b.name}: ₪${Math.round(b.kpis.spend).toLocaleString()} spend, ROAS ${r != null ? r.toFixed(2) + "×" : "n/a"}, CTR ${(b.kpis.ctr * 100).toFixed(2)}%, ${b.kpis.purchases} purchases`
        );
      }
    }
    lines.push("");
  }

  // ── Affiliate deep-dive top 3 by sales ────────────────────────────
  if (input.affiliateDeepDive && input.affiliateDeepDive.affiliates.length > 0) {
    const aff = [...input.affiliateDeepDive.affiliates].sort((a, b) => b.sales - a.sales);
    lines.push("Affiliates (top by sales):");
    for (const a of aff.slice(0, 3)) {
      lines.push(`  - ${a.affiliateName || a.couponCode || a.affiliateMemberId}: ₪${Math.round(a.sales).toLocaleString()}, ${a.orders} orders`);
    }
    lines.push("");
  }

  // ── Red flags: restock + ROAS collapse ────────────────────────────
  if (input.restockAlerts && input.restockAlerts.flags.length > 0) {
    lines.push(`Restock alerts: ${input.restockAlerts.flags.length} hero products restocked this week (potential sales recovery).`);
    for (const f of input.restockAlerts.flags.slice(0, 3)) {
      lines.push(`  - ${f.title} (gap ${f.gapDays}d, prior revenue ₪${Math.round(f.priorRevenue).toLocaleString()})`);
    }
    lines.push("");
  }
  if (input.roasCollapseAlerts && input.roasCollapseAlerts.flags.length > 0) {
    lines.push(`ROAS collapse alerts: ${input.roasCollapseAlerts.flags.length} campaigns flagged.`);
    for (const c of input.roasCollapseAlerts.flags.slice(0, 3)) {
      lines.push(`  - ${c.campaignName} (${c.brandName}): ROAS ${c.roas.toFixed(2)}×, spend ₪${Math.round(c.spend).toLocaleString()}`);
    }
    lines.push("");
  }

  // ── Competitive landscape (RivalSweeper) ──────────────────────────
  // Gives the agent external context so a soft week can be explained by
  // the market ("3 rivals at 40% off"), not just described.
  const cwHasSignals =
    input.competitorWeek != null &&
    input.competitorWeek.competitors.some((entry) => entry.change.kind !== "no_data");
  if (input.competitorWeek && cwHasSignals) {
    const cw = input.competitorWeek;
    const maxOff =
      cw.totals.maxDiscountPct !== null ? `, deepest discount ${Math.round(cw.totals.maxDiscountPct)}%` : "";
    lines.push(
      `Competitors (${cw.totals.tracked} tracked): ${cw.totals.openedPromo} opened promos this week${maxOff}.`
    );
    for (const entry of cw.competitors.slice(0, 5)) {
      lines.push(`  - ${entry.name} (${entry.domain}): ${entry.change.summary.en}`);
    }
    lines.push(
      "  When our KPIs dipped and a competitor opened/deepened a promo, connect the two explicitly."
    );
    lines.push("");
  } else {
    // Automated competitor snapshots are not flowing yet (fresh monitoring) —
    // fall back to the latest manual intel sweep so the executive summary
    // still has competitive context instead of silence.
    lines.push(
      `Competitor intel (manual sweep, ${COMPETITOR_INTEL_LATEST.generatedAt} — automated tracking still filling):`
    );
    for (const c of COMPETITOR_INTEL_LATEST.competitors) {
      lines.push(`  - ${c.name}: ${c.move}`);
    }
    lines.push("");
  }

  // Live tracked activity (RivalSweeper) — real numbers the summary may cite.
  const activity = (input.competitorActivity ?? []).filter(
    (a) => (a.adsActive ?? 0) > 0 || a.news.length > 0 || a.homepageLinks.length > 0
  );
  if (activity.length > 0) {
    lines.push("Live competitor tracking (RivalSweeper, current):");
    for (const a of activity) {
      const bits: string[] = [];
      if ((a.adsActive ?? 0) > 0) {
        bits.push(
          `${a.adsActive} active Meta ads${a.adHeadlines.length ? ` (themes: ${a.adHeadlines.slice(0, 2).join(" / ")})` : ""}`
        );
      }
      if (a.homepageLinks.length > 0) bits.push(`homepage pushes: ${a.homepageLinks.slice(0, 3).join(", ")}`);
      if (a.news.length > 0) bits.push(`press: ${a.news.slice(0, 1).map((n) => n.title).join("")}`);
      lines.push(`  - ${a.name}: ${bits.join(" · ")}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function buildPrompt(input: BiWeeklyCommentaryInput, digest: string): string {
  const lang = input.locale === "he" ? "Hebrew" : "English";
  return [
    `You are the Hiloomy BI agent writing the executive summary for this week's report.`,
    "",
    `Period: ${input.periodStart} → ${input.periodEnd}`,
    `Output language: ${lang}`,
    "",
    `DATA DIGEST:`,
    digest,
    "",
    `HARD RULES — break any of these and the output is unusable:`,
    `  1. MAX 3 insights, MAX 3 actions. Each must be ≤ 25 words.`,
    `  2. NO REPETITION: every insight cites a unique fact. No action restates an insight.`,
    `     If you mention "RECETTE 702 restocked" in an insight, the corresponding action`,
    `     must add new info (e.g. "Boost +20% budget by Tuesday"), not repeat it.`,
    `  3. Wrap KPI numbers, campaign/product names, percentages in **bold** Markdown.`,
    `     Example: "**RECETTE 702** drove **₪184,067** at **ROAS 7.5×**."`,
    `  4. Actions MUST start with a specific decisive verb.`,
    input.locale === "he"
      ? `     In Hebrew output use HEBREW verbs ONLY: הגדילו / עצרו / בדקו / חדשו מלאי / שלחו / השיקו / שכפלו / הסיטו.` +
        ` FORBIDDEN in Hebrew text: Scale, Pause, Kill, Test and any other English verb.`
      : `     Allowed: Scale / Pause / Test / Restock / Email / Launch / Duplicate / Kill / Shift.`,
    `     FORBIDDEN: "Consider", "Explore", "Look into", "Continue to", "Maintain", "שקלו", "בחנו אפשרות".`,
    `  5. Headline: ≤ 18 words, one sentence, captures THE story. Use bold for the biggest number.`,
    `  6. Be scannable. Founder reads this in 15 seconds, not 60.`,
    ...(input.locale === "he"
      ? [
          `  7. Hebrew style (RTL-safe): no +/- signs before numbers — write "עלה 17.8%" / "ירד 50%".`,
          `     Date ranges in words ("בין 4 ל8 באוגוסט"), never "04-06/08". No connector hyphen between`,
          `     Hebrew prefix letters and numbers/foreign words: write "ב31", "הROAS", "לShopify".`,
          `  8. Explain a professional term the first time it appears: "ROAS 5.3 (כל שקל פרסום החזיר 5.3 שקל)".`
        ]
      : []),
    `  9. ACTION AUTHORITY — act only where the founder has a direct lever:`,
    `     the STORE itself (pages, offers, product pages, checkout), CAMPAIGNS (budget,`,
    `     creative, pause/scale), INVENTORY, and EMAIL/notifications.`,
    `     You are a data analyst, NOT a manager of people. NEVER instruct hiring, firing,`,
    `     removing partners/affiliates, or setting ultimatums to people ("אחרת תוסרנה" is`,
    `     forbidden). About people you may at most suggest a CHECK ("שווה לבדוק מול X את Y")`,
    `     — one such suggestion maximum, and only when the data justifies it.`,
    "",
    `Output JSON object with these fields:`,
    `{`,
    `  "headline": "<one sentence with **bold** on the headline number>",`,
    `  "insights": ["<insight 1 with **bold** numbers>", "<insight 2>", "<insight 3>"],`,
    `  "actions": ["<Scale|Pause|Test|... action 1 with **bold** entity>", "<action 2>", "<action 3>"]`,
    `}`
  ].join("\n");
}

export async function generateWeeklyBiCommentary(input: BiWeeklyCommentaryInput): Promise<BiWeeklyCommentary | null> {
  if (!isBiAgentConfigured()) return null;
  const digest = buildDigest(input);
  if (digest.trim().length < 30) return null; // no data → no commentary

  try {
    // Prefer the BI analytics agent for this (it's an analytics task, not
    // a creative one). Falls back to the creative agent if BI returns
    // a bad shape — both can do JSON output via the same instruction.
    let parsed: { headline?: string; insights?: string[]; actions?: string[] };
    try {
      parsed = await askBiAgentJson<typeof parsed>({
        question: buildPrompt(input, digest),
        jsonHint: 'object with headline:string, insights:string[3], actions:string[3]',
        timeoutMs: 60_000
      });
    } catch {
      parsed = await askCreativeAgentJson<typeof parsed>({
        question: buildPrompt(input, digest),
        jsonHint: 'object with headline:string, insights:string[3], actions:string[3]',
        timeoutMs: 60_000
      });
    }

    const insights = Array.isArray(parsed.insights) ? parsed.insights.filter(Boolean).slice(0, 5) : [];
    const actions = Array.isArray(parsed.actions) ? parsed.actions.filter(Boolean).slice(0, 5) : [];
    const headline = (parsed.headline ?? "").trim();
    if (!headline && insights.length === 0 && actions.length === 0) return null;

    return {
      headline: headline || (input.locale === "he" ? "סיכום שבועי" : "Weekly executive summary"),
      insights,
      actions,
      agent: "brandzp-bi",
      generatedAt: new Date().toISOString()
    };
  } catch (err) {
    console.error("[weekly-bi-commentary] failed:", err);
    return null;
  }
}
